spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    root: INFO
    com.daou.sabangnetserver: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  charset:
    console: UTF-8
---

spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: INFO
    com.daou.sabangnetserver: DEBUG
  file:
    path: /home/ec2-user/fulfillment-admin/app/logs
    name: sabangnetserver.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  charset:
    console: UTF-8
    file: UTF-8
